# Cloudflare Pages Configuration
# This file configures the build settings for Cloudflare Pages

name: somatic-canticles

# Build settings
build:
  command: npm run build
  output_directory: out
  
# Environment variables (set in Cloudflare dashboard)
# - NEXTAUTH_SECRET
# - AUTH_SECRET  
# - NEXTAUTH_URL
# - CLOUDFLARE_ACCOUNT_ID
# - CLOUDFLARE_API_TOKEN

# Headers
headers:
  - pattern: /canticles/*
    headers:
      Cache-Control: public, max-age=31536000, immutable
  - pattern: /_next/static/*
    headers:
      Cache-Control: public, max-age=31536000, immutable

# Redirects - Proxy API requests to the Worker
redirects:
  - source: /api/*
    destination: https://khaloree.tryambakam.space/api/:splat
    status: 200
